"""Which ANALYSED moments he has taken out of the generator's hands.

A generated cue is keyed by the analysis moment that produced it
(SpectraTrigger.generator_key, "section:<raw ms>"). Two human gestures end
the generator's ownership of that moment:

  edited   — he changed the cue through the trigger API. The row stays,
             under the SAME id, as source="authored" with its key cleared
             (spectra/api/triggers.py's ownership-transfer rule), so
             nothing on the row itself still names the moment it came from.
  deleted  — he removed the cue.

Before re-analysis existed, losing that link cost nothing: a stored cue was
only ever regenerated by an explicit "⟳ Generate" press. Since a stale
song is now re-planned on its next play (and the whole library through
Sonic), the generator would quietly put a deleted cue back, or seed a
second cue beside the one he edited. This sidecar is what stops it: every
key recorded here is excluded from planning for that song, for good.

A SIDECAR, not a field on the trigger, for the same reason the profile-sync
ledger is one (spectra/services/profile_sync_ledger.py): a deleted row has
no row left to carry the fact, and an edited row's key is deliberately
cleared. It lives NEXT TO triggers.json (config.TRIGGERS_FILE's own
directory) and is resolved at call time, so anything that repoints the
trigger store — every test and check script does — repoints this with it.

Shape: {uri: {generator_key: {"kind": "edited"|"deleted", "at": iso8601}}}.
Recording is best-effort by design: the trigger write it follows has
already landed, and a failed claim write is logged loudly rather than
undoing his edit.
"""
from __future__ import annotations

import json
import logging
import os
import tempfile
import threading
from datetime import datetime, timezone
from pathlib import Path
from typing import Literal

from spectra import config

logger = logging.getLogger(__name__)

ClaimKind = Literal["edited", "deleted"]

_lock = threading.Lock()


def claims_path() -> Path:
    return config.TRIGGERS_FILE.parent / "analysed_claims.json"


def load_all() -> dict[str, dict[str, dict]]:
    path = claims_path()
    if not path.exists():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:
        logger.warning("analysed_claims.json parse failed: %s", exc)
        return {}
    if not isinstance(data, dict):
        return {}
    return {uri: keys for uri, keys in data.items() if isinstance(keys, dict)}


def claimed_keys(uri: str) -> set[str]:
    """Every generator_key he has edited or deleted on this song."""
    return set(load_all().get(uri, {}))


def _save(data: dict) -> None:
    path = claims_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=path.name, suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            json.dump(data, fh, indent=2, sort_keys=True)
        os.replace(tmp, path)
    except BaseException:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


def record(uri: str, generator_key: str, kind: ClaimKind) -> None:
    """Note that `generator_key` on `uri` is his now. Never raises."""
    if not uri or not generator_key:
        return
    try:
        with _lock:
            data = load_all()
            data.setdefault(uri, {})[generator_key] = {
                "kind": kind,
                "at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
            }
            _save(data)
        logger.info("analysed cue %s on %s %s by hand — the generator will "
                    "not put it back", generator_key, uri, kind)
    except Exception:
        logger.exception("could not record that analysed cue %s on %s was %s "
                         "— a later re-analysis may restore it", generator_key,
                         uri, kind)


def record_from_row(uri: str, previous: dict | None, kind: ClaimKind) -> None:
    """Record a claim when `previous` (the raw stored row an edit replaced or
    a delete removed) was a GENERATED cue. Anything else — a new trigger,
    or one that was already his — is not a claim and is ignored."""
    if not isinstance(previous, dict) or previous.get("source") != "generated":
        return
    key = previous.get("generator_key")
    if key:
        record(uri, key, kind)
